### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by jamra** [claunia/plist-cil#1]
Can you please post an example of how to use this library?

**Comment by 3breadt** [comment]
Hi,

please refer to https://github.com/3breadt/dd-plist/blob/master/README.md

BR,
Daniel
Am 21.08.2015 12:22 vorm. schrieb "Jacob Amrany" <notifications@github.com>:

**Comment by claunia** [comment]
@3breadt probably I should copy your examples section, with your permission :stuck_out_tongue: 

While 99% of the code will be the same between Java and C#, it is confusing for people that know 0 about java, not to say they have to visit both sites.

What do you think?

**Comment by 3breadt** [comment]
@claunia no problem, feel free to copy it.
