### ISSUE TITLE
Error on .NET Core LTS

### ISSUE THREAD

**Issue by bradley-fastorientation** [claunia/plist-cil#13]
I am using the [LTS version](https://www.microsoft.com/net/download/core#/lts) of .NET Core on macOS 10.12.2. My output of `dotnet --version` is `1.0.0-preview2-003156`.

When I try to include version `1.14.0` in my `project.json` I get the following errors:

> error: Package plist-cil 1.14.0 is not compatible with netcoreapp1.0         (.NETCoreApp,Version=v1.0). Package plist-cil 1.14.0 supports: net (.NETFramework,Version=v0.0)
> error: One or more packages are incompatible with .NETCoreApp,Version=v1.0.

Here is the `project.json` that I used:
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {},
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.3"
        },
	"plist-cil": "1.14.0"
      },
      "imports": "dnxcore50"
    }
  }
}
```

**Comment by claunia** [comment]
This is expected, .NET Core is not yet supported.

**Comment by bradley-fastorientation** [comment]
You should remove .NET Core from your list of [requirements](https://github.com/claunia/plist-cil#requirements) then. It implies it is supported.

**Comment by claunia** [comment]
It is compatible with a different target, other users have used it. However that usage is unsupported. As soon as I can I will add proper support, plus new features.

**Comment by claunia** [comment]
@bradley-fastorientation sorry but .NET Core preview2 will not be supported. VS2017-release will contain next .NET Core LTS so it's better to prepare for it directly.
