### ISSUE TITLE
Better support for UIDs

### ISSUE THREAD

**Issue by qmfrederik** [claunia/plist-cil#3]
plist-cil is one of the few .NET plist libraries that cna handle UIDs properly, congrats to that :-).

However, `UID`s are essentially numbers, and it would be great if you could change the `UID` class so that:
- It takes an integer as a parameter (not sure what the name is used for)
- When serializing the integer value, it follows the same rule as for NSNumbers -- if the value is less than `byte.MaxValue`, only a single byte is used, if the value is less than `ushort.MaxValue`, to bytes are used, and so forth.

Cheers

**Comment by claunia** [comment]
Hi @qmfrederik.

plist-cil  is basically a C# port of https://github.com/3breadt/dd-plist so maybe both me and @3breadt can benefit from that changes?
