### ISSUE TITLE
Roundtrip of the value 0 for reals

### ISSUE THREAD

**Issue by qmfrederik** [claunia/plist-cil#34]
It turns out you can have multiple representations of the value `0` for reals. Until now, I always saw `0.0`, but you can also have `0.000000` like this:

```xml
<key>TimeZoneOffsetFromUTC</key>
<real>0.000000</real>
```

If we want to roundtrip, we should keep the number of significant digits somewhere in the NSNumber object.

**Comment by claunia** [comment]
Is it really needed? Can you attach a proposal.

**Comment by qmfrederik** [comment]
I think we can close this for now, I don't need it currently. I'll reopen this if I ever need it :)
