### ISSUE TITLE
Fails to load in Xamarin.Android.

### ISSUE THREAD

**Issue by JunielKatarn** [claunia/plist-cil#49]
See sample project: https://github.com/JunielKatarn/PlistDroid

Adding `plist-cil` as a dependency throws build errors due to missing reference to `System.Memory`.
```
Could not load assembly 'System.Memory' during startup registration.
```

Adding `System.Memory` (version >=4.5) NuGet package solves the build issue, but fails again at runtime (the application doesn't load) with this message:
```
F/monodroid-assembly( 9097): Could not load assembly 'System.Memory' during startup registration.
```

This may be related to Xamarin.Android still being based on the Mono framework.
Is this something that can be fixed by adding certain platform target frameworks to the plist-cil's build process?

**Comment by JunielKatarn** [comment]
Fixed by using https://www.nuget.org/packages/CoreCompat.plist-cil.

**Comment by claunia** [comment]
@JunielKatarn hi, I released a new version that should work, try with https://www.nuget.org/packages/plist-cil/1.60.0

**Comment by JunielKatarn** [comment]
Thanks! I've verified this new version works.

**Comment by claunia** [comment]
Me alegra saberlo!
