### ISSUE TITLE
Updated release on NuGet

### ISSUE THREAD

**Issue by qmfrederik** [claunia/plist-cil#55]
It looks like there hasn't been any release of plist-cil for a while. A couple of PRs got merged a while ago (especially #51).

Do you think you could publish a new release to NuGet?

Thanks!

**Comment by claunia** [comment]
@qmfrederik sorry I was in the middle of moving houses and without internet, I will do a release asap.

**Comment by claunia** [comment]
@qmfrederik https://www.nuget.org/packages/plist-cil/1.60.0 now we should not need your fork in nuget :p?

**Comment by qmfrederik** [comment]
Awesome! I'll try to get our dependencies updated some time next week, and clean up NuGet after that.
