### ISSUE TITLE
Next version numbering

### ISSUE THREAD

**Issue by claunia** [claunia/plist-cil#61]
This is a RFC as some changes from @qmfrederik have been incompatible changes at API level.

Should next version be 2.0 or do we need more features for that?

**Comment by qmfrederik** [comment]
That's up to you - I don't really have a strong opinion about version numbers 😄 .

**Comment by claunia** [comment]
you're not being helpful :angry:

**Comment by qmfrederik** [comment]
In that case, let's go for 2.0 :)

**Comment by qmfrederik** [comment]
@claunia Any chance you can cut a new release? #56, #57, #58, #59 and #60 aren't in the latest release yet 😄

**Comment by qmfrederik** [comment]
Thanks!
